name: Warn about PRs from forks via comment

on:
  pull_request:
    branches:
      - main
    types:
      - opened

jobs:
  warn-forks:
    runs-on: ubuntu-latest
    if: github.event.pull_request.head.repo.full_name != 'the-turing-way/teams-as-code'
    permissions:
      issues: write
      pull-requests: write
    steps:
      - name: Post comment
        uses: peter-evans/create-or-update-comment@v5
        with:
          issue-number: ${{ github.event.number }}
          body: >-
            Oh no! It seems you've opened this Pull Request from a fork :frowning_face:
            
            So you know, the tests will likely fail because they require secrets,
            which aren't available when workflows run from forks. Please reopen your
            Pull Request from a branch of this repository.

            If you don't have write access to this repository, because you aren't
            yet a member of a team, please ask someone from the team you are trying
            to update to open the Pull Request on your behalf.

            Thank you for keeping our teams up-to-date!
